apiVersion: v1
kind: ConfigMap
metadata:
  name: max-bot-config
  namespace: default
data:
  config.yaml: |
    max_token: ${MAX_TOKEN}
    user_service_url: ${USER_SERVICE_URL}
    customer_service_url: ${CUSTOMER_SERVICE_URL}

